baseURL = 'https://www.chleynx.top/'
languageCode = 'zh-cn'
title = 'chleynx blog'
theme = 'archie'

[pagination]
pagerSize = 10

[params]
mode = 'auto'
useCDN = false
subtitle = ''
description = ''

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/chensonghi'

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 1

[[menu.main]]
name = 'Tags'
url = '/tags'
weight = 2

[[menu.main]]
name = 'About'
url = '/about'
weight = 3
