baseURL = 'https://www.chleynx.top/'
languageCode = 'zh-cn'
title = "chleynx's blog"
theme = 'archie'

[pagination]
pagerSize = 10

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

[params]
mode = 'toggle'
useCDN = false
subtitle = ''
description = ''

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/chensonghi'

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 1

[[menu.main]]
name = 'Tags'
url = '/tags'
weight = 2

[[menu.main]]
name = 'About'
url = '/about'
weight = 3
